#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jul 03, 2019 01:25:18 PM -03  platform: Windows NT

import sys
import controllers.Pacientes as ctrl

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global pacientes
    global nombre
    nombre = tk.StringVar()
    global apellido
    apellido = tk.StringVar()
    global dni
    dni = tk.StringVar()
    global fecha
    fecha = tk.StringVar()
    global nacion
    nacion = tk.StringVar()
    global sexo
    sexo = tk.StringVar()

def nuevoPaciente():
    success = ctrl.crearPaciente(nombre.get(),apellido.get(),dni.get(),fecha.get(),sexo.get(),nacion.get())
    print(success)
    if(success != None):
        print("Se creo exitosamente")
        import views.abm_pacientes as abm_pacientes
        abm_pacientes.top.insertarUltimo(success)
        abm_pacientes.top.clear()
    else:
        print("Error en la creacion")

def getAll():
    pacientes = ctrl.buscarAllPacientes()
    return pacientes
    

def destroy_window():
    print('abm_pacientes_support.destroy_window')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import abm_pacientes
    abm_pacientes.vp_start_gui()



