#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jul 10, 2019 01:52:08 PM -03  platform: Windows NT

import sys
import controllers.Pacientes as ctrl

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global buscarPaciente
    buscarPaciente = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
def getAll():
    return ctrl.buscarAllPacientes()

def getPorApellido(apellido):
    pacientes = ctrl.buscarPacientesPorApellido(apellido)
    if (pacientes == None):
        print("Error en la busqueda")
    else:
        print("Se buscaron pacientes por apellido")
        import views.buscarpaciente as vista
        vista.top.insertar(pacientes)
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None