#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jul 11, 2019 08:23:36 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import controllers.Gestos as ctrl
import controllers.Estudio as estudio

def set_Tk_var():
    global pacienteLabel
    pacienteLabel = tk.StringVar()
    pacienteLabel.set('')
    global medicoLabel
    medicoLabel = tk.StringVar()
    medicoLabel.set('')

# def destroy_window():
#     print('estudios_support.destroy_window')
#     sys.stdout.flush()

def getAllGestos():
    return ctrl.buscarAllGestos()

def comenzarEstudio(paciente,medico,gestos):
    estudio.comenzarEstudio(paciente,medico,gestos)
    destroy_window()



def calibrarCamara():
    estudio.calibrar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import estudios
    estudios.vp_start_gui()




