#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jul 03, 2019 01:16:10 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import views.gestos_support as gestos_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    gestos_support.set_Tk_var()
    top = abmGestos (root)
    gestos_support.init(root, top)
    root.mainloop()

w = None
def create_abmGestos(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt, top
    rt = root
    w = tk.Toplevel (root)
    gestos_support.set_Tk_var()
    top = abmGestos (w)
    gestos_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_abmGestos():
    global w
    w.destroy()
    w = None

class abmGestos:
    def __init__(self, top=None):
        self.gestos = []
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 18 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("647x483+403+162")
        top.title("gestos")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.descripcionGestoLabel = ttk.Label(top)
        self.descripcionGestoLabel.place(relx=0.068, rely=0.248, height=19
                , width=140)
        self.descripcionGestoLabel.configure(background="#d9d9d9")
        self.descripcionGestoLabel.configure(foreground="#000000")
        self.descripcionGestoLabel.configure(font="TkDefaultFont")
        self.descripcionGestoLabel.configure(relief="flat")
        self.descripcionGestoLabel.configure(text='''Descripción de gesto''')

        self.descripcionGestoInput = ttk.Entry(top)
        self.descripcionGestoInput.place(relx=0.325, rely=0.248, relheight=0.043
                , relwidth=0.402)
        self.descripcionGestoInput.configure(textvariable=gestos_support.descripcion)
        self.descripcionGestoInput.configure(takefocus="")
        

        self.punto1Input = ttk.Entry(top)
        self.punto1Input.place(relx=0.742, rely=0.248, relheight=0.043
                , relwidth=0.04)
        self.punto1Input.configure(textvariable=gestos_support.punto1)
        self.punto1Input.configure(takefocus="")
        

        self.punto2Input = ttk.Entry(top)
        self.punto2Input.place(relx=0.827, rely=0.248, relheight=0.043
                , relwidth=0.04)
        self.punto2Input.configure(textvariable=gestos_support.punto2)
        self.punto2Input.configure(takefocus="")
        

        self.abmgestos = tk.Message(top)
        self.abmgestos.place(relx=0.046, rely=0.021, relheight=0.13
                , relwidth=0.896)
        self.abmgestos.configure(background="#09d8d8")
        self.abmgestos.configure(font=font9)
        self.abmgestos.configure(foreground="#000000")
        self.abmgestos.configure(highlightbackground="#d9d9d9")
        self.abmgestos.configure(highlightcolor="black")
        self.abmgestos.configure(text='''ABM Gestos''')
        self.abmgestos.configure(width=580)

        self.punto1 = tk.Message(top)
        self.punto1.place(relx=0.711, rely=0.186, relheight=0.048
                , relwidth=0.093)
        self.punto1.configure(background="#d9d9d9")
        self.punto1.configure(font=font10)
        self.punto1.configure(foreground="#000000")
        self.punto1.configure(highlightbackground="#d9d9d9")
        self.punto1.configure(highlightcolor="black")
        self.punto1.configure(text='''Punto 1''')
        self.punto1.configure(width=60)

        self.punto2 = tk.Message(top)
        self.punto2.place(relx=0.804, rely=0.186, relheight=0.048
                , relwidth=0.093)
        self.punto2.configure(background="#d9d9d9")
        self.punto2.configure(font=font10)
        self.punto2.configure(foreground="#000000")
        self.punto2.configure(highlightbackground="#d9d9d9")
        self.punto2.configure(highlightcolor="black")
        self.punto2.configure(text='''Punto 2''')
        self.punto2.configure(width=60)

        self.grabarInput = ttk.Button(top)
        self.grabarInput.place(relx=0.526, rely=0.89, height=25, width=76)
        self.grabarInput.configure(takefocus="")
        self.grabarInput.configure(text='''Grabar''')
        self.grabarInput.configure(command=gestos_support.nuevoGesto)

        self.salirInput = ttk.Button(top)
        self.salirInput.place(relx=0.711, rely=0.89, height=25, width=76)
        self.salirInput.configure(command=gestos_support.destroy_window)
        self.salirInput.configure(takefocus="")
        self.salirInput.configure(text='''Salir''')

        self.gestosLista = ScrolledListBox(top)
        self.gestosLista.place(relx=0.046, rely=0.352, relheight=0.487
                , relwidth=0.898)
        self.gestosLista.configure(background="white")
        self.gestosLista.configure(disabledforeground="#a3a3a3")
        self.gestosLista.configure(font="TkFixedFont")
        self.gestosLista.configure(foreground="black")
        self.gestosLista.configure(highlightbackground="#d9d9d9")
        self.gestosLista.configure(highlightcolor="#d9d9d9")
        self.gestosLista.configure(selectbackground="#c4c4c4")
        self.gestosLista.configure(selectforeground="black")
        self.gestosLista.configure(width=10)

        self.actualizar()

        self.nuevoButton = ttk.Button(top)
        self.nuevoButton.place(relx=0.155, rely=0.89, height=25, width=76)
        self.nuevoButton.configure(takefocus="")
        self.nuevoButton.configure(text='''Nuevo''')

        self.editButton = ttk.Button(top)
        self.editButton.place(relx=0.34, rely=0.89, height=25, width=76)
        self.editButton.configure(takefocus="")
        self.editButton.configure(text='''Editar''')


    def actualizar(self):
        self.gestos = gestos_support.getAll()
        for item in self.gestos:
            self.gestosLista.insert(tk.END,"{}, [{},{}]".format(item.descripcion,item.inicio,item.fin))
    
    def insertarUltimo(self,item):
        self.gestosLista.insert(tk.END,"{}, [{},{}]".format(item.descripcion,item.inicio,item.fin))    

    def clear(self):
        gestos_support.descripcion.set("")
        gestos_support.punto1.set("")
        gestos_support.punto2.set("")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





