#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Aug 05, 2019 08:01:43 PM -03  platform: Windows NT

import sys
import controllers.Estudio as ctrl
import controllers.ComputerVision as cv
import views.progress as progress
import threading

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global pacientes
    pacientes = tk.StringVar()
    global isProcessed
    isProcessed = tk.IntVar()
    global steps
    steps = tk.IntVar()
    global maximo
    maximo = tk.IntVar()

def destroy_window():
    print('historial_support.destroy_window')
    sys.stdout.flush()

def getEstudios(flag):
    return ctrl.getAllEstudios(flag)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def procesarVideo(id):
    global w
    w.resetBar()
    x = threading.Thread(target=cv.procesarvideo,args=(id,callbackStep,callbackMax))
    x.start()

def callbackStep(step):
    #import views.historial as historial
    print("Vamos por el paso: {}".format(step))
    global w
    w.setProgress(step)

def callbackMax(maximo):
    global w
    w.setMaximo(maximo)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import historial
    historial.vp_start_gui()




