#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Aug 05, 2019 08:01:33 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import views.historial_support as historial_support
import views.estudios as estudios

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    historial_support.set_Tk_var()
    top = historial (root)
    historial_support.init(root, top)
    root.mainloop()

w = None
def create_historial(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt, top
    rt = root
    w = tk.Toplevel (root)
    historial_support.set_Tk_var()
    top = historial (w)
    historial_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_historial(): 
    global w
    w.destroy()
    w = None

class historial:
    def __init__(self, top=None):
        self.estudios = []
        self.estudioSelected = None
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 24 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+436+167")
        top.title("Estudios")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#ffffff")

        self.titulo = tk.Message(top)
        self.titulo.place(relx=0.233, rely=0.089, relheight=0.096
                , relwidth=0.55)
        self.titulo.configure(background="#d9d9d9")
        self.titulo.configure(font=font10)
        self.titulo.configure(foreground="#000000")
        self.titulo.configure(highlightbackground="#d9d9d9")
        self.titulo.configure(highlightcolor="black")
        self.titulo.configure(text='''Estudios''')
        self.titulo.configure(width=330)

        self.labelP = ttk.Label(top)
        self.labelP.place(relx=0.067, rely=0.244, height=19, width=66)
        self.labelP.configure(background="#d9d9d9")
        self.labelP.configure(foreground="#000000")
        self.labelP.configure(font="TkDefaultFont")
        self.labelP.configure(relief="flat")
        self.labelP.configure(text='''Paciente''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.salir = ttk.Button(top)
        self.salir.place(relx=0.667, rely=0.844, height=25, width=76)
        self.salir.configure(command=historial_support.destroy_window)
        self.salir.configure(takefocus="")
        self.salir.configure(text='''Salir''')

        self.abrir = ttk.Button(top)
        self.abrir.place(relx=0.458, rely=0.844, height=25, width=76)
        self.abrir.configure(takefocus="")
        self.abrir.configure(text='''Abrir''')

        self.procesar = ttk.Button(top)
        self.procesar.place(relx=0.183, rely=0.844, height=25, width=120)
        self.procesar.configure(takefocus="")
        self.procesar.configure(text='''Procesar estudios''')
        self.procesar.configure(command=self.getVideoFromList)

        self.lista = ScrolledListBox(top)
        self.lista.place(relx=0.133, rely=0.389, relheight=0.320
                , relwidth=0.735)
        self.lista.configure(background="white")
        self.lista.configure(disabledforeground="#a3a3a3")
        self.lista.configure(font="TkFixedFont")
        self.lista.configure(foreground="black")
        self.lista.configure(highlightbackground="#d9d9d9")
        self.lista.configure(highlightcolor="#d9d9d9")
        self.lista.configure(selectbackground="#c4c4c4")
        self.lista.configure(selectforeground="black")
        self.lista.configure(width=10)
        self.lista.configure(listvariable=historial_support.pacientes)

        self.pacienteLabel = ttk.Label(top)
        self.pacienteLabel.place(relx=0.2, rely=0.244, height=19, width=286)
        self.pacienteLabel.configure(background="#7a77d8")
        self.pacienteLabel.configure(foreground="#000000")
        self.pacienteLabel.configure(font=font9)
        self.pacienteLabel.configure(relief="flat")

        self.buscarButton = ttk.Button(top)
        self.buscarButton.place(relx=0.733, rely=0.233, height=25, width=76)
        self.buscarButton.configure(takefocus="")
        self.buscarButton.configure(text='''Buscar''')

        self.flag = tk.BooleanVar()
        # self.style.map('TCheckbuself.flag = tk.BooleanVar()tton',background=
        #     [('selected', _bgcolor), ('active', _ana2color)])
        self.isProcessedChxb = ttk.Checkbutton(top)
        self.isProcessedChxb.place(relx=0.35, rely=0.311, relwidth=0.235
                , relheight=0.0, height=21)
        self.isProcessedChxb.config(variable=self.flag)
        self.isProcessedChxb.config(takefocus="")
        self.isProcessedChxb.config(text='''No procesados''')
        self.isProcessedChxb.config(width=141)
        self.isProcessedChxb.config(command=self.handlerCB)

        self.TProgressbar = ttk.Progressbar(top)
        self.TProgressbar.place(relx=0.133, rely=0.750, relwidth=0.733
                , relheight=0.0, height=22)
        
        self.actualizarLista()

    def getVideoFromList(self):
        haySeleccionados = self.lista.curselection()
        print("Seleccionados: {}".format(haySeleccionados))
        if(haySeleccionados != ()):
            seleccionados = haySeleccionados
            for selected in seleccionados:
                print("Seleccionado: {}".format(selected))
                #self.gestosSelected.append(self.gestos.index())
                for index,estudio in enumerate(self.estudios):
                    if(selected == index):
                        #self.estudioSelected.append(estudio)
                        print("Estudio {}, descripcion: {}".format(index,estudio.id))
                        historial_support.procesarVideo("{}".format(estudio.id))

    def handlerCB(self):
        self.flag.set(not self.flag.get())
        self.actualizarLista()

    def setProgress(self,step):
        self.TProgressbar.step(step)

    def setMaximo(self,maximo):
        self.TProgressbar.config(maximum=maximo)
    
    def resetBar(self):
        self.TProgressbar.config(value=0)

    def actualizarLista(self):
        self.clearTable()
        self.estudios = historial_support.getEstudios(self.flag.get())
        for index, est in enumerate(self.estudios):
            #print(est)
            self.lista.insert(index,"Paciente: {}, {} - {}".format(est.paciente.apellido,est.paciente.nombre,est.fecha))
    def clearTable(self):
        self.lista.delete(0,tk.END)
        self.estudios = []
   
# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





